from moeda import *
n = float(input('Digite um número: '))
print(' ')
print(f'O de valor {n} com aumento de 10% é {aumenta(n)}')
print(' ')
print(f'O de valor {n} com desconto de 10% é {diminui(n)}')
print(' ')
print(f'O de valor {n} dobrado é {dobro(n)}')
print(' ')
print(f'A metade de {n} é {metade(n)}')